export const MILLISECONDS_IN_SECOND = 1000;
export const SECONDS_IN_MINUTE = 60;
export const MINUTES_IN_HOUR = 60;

export const HOURS_IN_DAY = 24;
export const MINUTES_IN_DAY = MINUTES_IN_HOUR * HOURS_IN_DAY;
export const SECONDS_IN_DAY = SECONDS_IN_MINUTE * MINUTES_IN_DAY;
export const SECONDS_IN_HOUR = SECONDS_IN_MINUTE * MINUTES_IN_HOUR;

export const MILLISECONDS_IN_MINUTE =
    MILLISECONDS_IN_SECOND * SECONDS_IN_MINUTE;
export const MILLISECONDS_IN_HOUR = MILLISECONDS_IN_MINUTE * MINUTES_IN_HOUR;
export const MILLISECONDS_IN_DAY = MILLISECONDS_IN_HOUR * HOURS_IN_DAY;
